services:
  postgres:
    image: postgres:16-alpine
    platform: linux/amd64
    volumes:
      - ninja_api_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ninja-api
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  django:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-container-env
    platform: linux/amd64
    env_file: docker-compose.env
    ports:
      - "8000:8000"
    volumes:
      - .:/app 
    command:
      [/bin/sleep, infinity]
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.4.1
    platform: linux/amd64
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    command: ["elasticsearch", "-Elogger.level=ERROR"]
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  kibana:
    image: docker.elastic.co/kibana/kibana:9.4.1
    platform: linux/amd64
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=false
      - LOGGING_ROOT_LEVEL=error
    ports:
      - "5601:5601"


volumes:
  ninja_api_data:
  esdata:
  