
#local development server
@baseUrl = http://localhost:8000

# add other environments here
# @baseUrl = http://staging-server:8080
# @baseUrl = http://production-server:8080

### get list of businesses
GET {{baseUrl}}/api/businesses
Content-Type: application/json

### get a business by id
GET {{baseUrl}}/api/businesses/1
Content-Type: application/json

### create a new businesses
POST {{baseUrl}}/api/businesses
Content-Type: application/json

{
    "business_name": "New Business",
    "contacts": [
        {
            "first_name": "First",
            "last_name": "Last",
            "address_line1": "123 Main St",
            "address_line2": "Suite 100",
            "city": "Anytown",
            "state": "CO",
            "zip_code": "12345",
            "email": "fist.last@host.com"
        },
        {
            "first_name": "First2",
            "last_name": "Last2",
            "address_line1": "456 Oak Ave",
            "city": "Somewhere",
            "state": "CO",
            "zip_code": "98765"
        }
    ]
}


