
#local development server
@baseUrl = http://localhost:8000
@esUrl = http://elasticsearch:9200
 

### es status
GET {{esUrl}} 
Content-Type: application/json


### search for businesses by name
GET {{baseUrl}}/api/search/businesses?business_name=COMPANY
Content-Type: application/json

### search for us senators by state
GET {{baseUrl}}/api/search/senators?state=CO
Content-Type: application/json


### search for us senators by name
GET {{baseUrl}}/api/search/senators?first_name=John&state=CO
Content-Type: application/json
 
