# Generated by Django 6.0.5 on 2026-05-24 07:44

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [migrations.RunSQL("CREATE SCHEMA IF NOT EXISTS ninja_api;")]
